allowBuilds:
  '@parcel/watcher': true
minimumReleaseAgeExclude:
  - vite@8.3.1
  - '@10coding/vite-plugin-jsx-scoped@0.5.0'
  - sass-embedded-all-unknown@1.105.1
  - sass-embedded-android-arm64@1.105.1
  - sass-embedded-android-arm@1.105.1
  - sass-embedded-android-riscv64@1.105.1
  - sass-embedded-android-x64@1.105.1
  - sass-embedded-darwin-arm64@1.105.1
  - sass-embedded-darwin-x64@1.105.1
  - sass-embedded-linux-arm64@1.105.1
  - sass-embedded-linux-arm@1.105.1
  - sass-embedded-linux-musl-arm64@1.105.1
  - sass-embedded-linux-musl-arm@1.105.1
  - sass-embedded-linux-musl-riscv64@1.105.1
  - sass-embedded-linux-musl-x64@1.105.1
  - sass-embedded-linux-riscv64@1.105.1
  - sass-embedded-linux-x64@1.105.1
  - sass-embedded-unknown-all@1.105.1
  - sass-embedded-win32-arm64@1.105.1
  - sass-embedded-win32-x64@1.105.1
  - sass-embedded@1.105.1
  - sass@1.105.1
overrides:
  'typescript': 'npm:typescript-native-bridge@latest'
